#!/data/data/com.termux/files/usr/bin/bash -e
clear
echo -e "\e[34m\e[1m RazY Setup Started"
apt-get update -y
apt-get upgrade -y
clear
cd.. && cd usr && cd bin && cd RazY-OS && mv razy-install /data/data/com.termux/files/usr/bin && cd .. && chmod +x razy-install && cd
echo -e "\e[34m\e[1m Enter this Command For Install RazY OS '\e[33m\e[1mrazy-install'"
